-- Anlegen der Indizes
-- Die in < > gesetzten Werte muessen angegeben werden
-- Erstellt: 21.03.2012 durch: Marchand

CREATE INDEX STATUS_WIRTSCHAFTSJAHR ON STATUS (WIRTSCHAFTSJAHR);
CREATE INDEX BETRIEBSDATEN_NAME ON BETRIEBSDATEN (VARIABLE);
CREATE INDEX KOMPLEXEVARIABLE_NAME ON KOMPLEXEVARIABLE (VARIABLE);
CREATE INDEX VARIABLE_NAME ON VARIABLE (NAME);
CREATE INDEX INDEX_BETRIEBSDATEN_ID ON BETRIEBSDATEN (BETRIEB_ID);
CREATE INDEX INDEX_MERKMALE ON VERSIONBETRIEB (BERECHNUNGSVERSION_ID, FILTER, MERKMAL1, MERKMAL2, MERKMAL3);
CREATE INDEX INDEX_VERSIONBETRIEB_BETRIEB_ID ON VERSIONBETRIEB (BETRIEB_ID);
CREATE UNIQUE INDEX INDEX_VERSIONBETRIEB ON VERSIONBETRIEB (BERECHNUNGSVERSION_ID ASC, BETRIEB_ID ASC);
CREATE UNIQUE INDEX INDEX_AUSWAHLVERSIONBETRIEB ON AUSWAHLVERSIONBETRIEB (AUSWERTUNGSZEITRAUM_ID ASC, VERSIONBETRIEB_ID ASC);
CREATE UNIQUE INDEX INDEX_GEWICHTUNGSFAKTOR ON GEWICHTUNGSFAKTOR(AUSWAHLVERSION_ID,GRUNDGESAMTHEIT_ID);
CREATE UNIQUE INDEX INDEX_AUSWERTUNGSZEITRAUM ON AUSWERTUNGSZEITRAUM(WIRTSCHAFTSJAHR_VON, WIRTSCHAFTSJAHR_BIS, BEREICH_ID);
CREATE UNIQUE INDEX INDEX_GRUNDGESAMTHEIT ON GRUNDGESAMTHEIT(JAHR, BEREICH_ID);

-- Temporäre Index
CREATE INDEX INDEX_VERGLEICH ON TMP_VERGLEICH (MERKMAL1, MERKMAL2, MERKMAL3);
CREATE INDEX INDEX_HOCHRECHNUNG ON TMP_HOCHRECHNUNG (BERECHNUNGSVERSION_ID, MERKMAL1, MERKMAL2, MERKMAL3);