-- Anlegen der Tabellen und Kommentare
-- Die in < > gesetzten Werte muessen angegeben werden
--
-- Erstellt: 05.12.2011 durch: Marchand

-- Hinweis: Damit eventuelle Umlaute korrekt Ã¼bernommen/dargestellt werden muss diese Datei in dem Format UTF8/UNIX vorliegen.
--          Dies ist mit den Konvertierungsfunktionen von Ultraedit zu bewerkstelligen (U8-UNIX).

------------------------------------------------------------

--create sequence hibernate_sequence start with 1;

CREATE TABLE ERHEBUNGSBEREICH(
   ID             NUMBER(10, 0) PRIMARY KEY,
   BEZEICHNUNG    VARCHAR2(10) NOT NULL,
   BESCHREIBUNG   VARCHAR2(50)
);

COMMENT ON TABLE ERHEBUNGSBEREICH IS 'Erhebungsbereich: Uebergreiffender Bereich';
COMMENT ON COLUMN ERHEBUNGSBEREICH.BEZEICHNUNG IS 'Name des Erhebungsbereichs';
COMMENT ON COLUMN ERHEBUNGSBEREICH.BESCHREIBUNG IS 'Beschreibung fuer den Erhebungsbereich';

CREATE TABLE BEREICH(
   ID             NUMBER(10, 0) PRIMARY KEY,
   BEZEICHNUNG    VARCHAR2(10) NOT NULL,
   BESCHREIBUNG   VARCHAR2(50),
   ERHEBUNGSBEREICH_ID   NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_ERHEBUNGSBEREICH FOREIGN KEY (ERHEBUNGSBEREICH_ID) REFERENCES ERHEBUNGSBEREICH (ID)
);

COMMENT ON TABLE BEREICH IS 'Bereich: Landwirtschaft, Forst oder Fischerei';
COMMENT ON COLUMN BEREICH.BEZEICHNUNG IS 'Name des Bereichs';
COMMENT ON COLUMN BEREICH.BESCHREIBUNG IS 'Beschreibung fuer den Bereich';

CREATE TABLE ABSCHNITT(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR abschnitt_seq) PRIMARY KEY,
   BEZEICHNUNG    VARCHAR2(10) NOT NULL,
   BESCHREIBUNG   VARCHAR2(80),
   KOMPLEX	  	  NUMBER(1),
   BEREICH_ID     NUMBER(10, 0),
   CONSTRAINT FK_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES ERHEBUNGSBEREICH (ID)
);

COMMENT ON TABLE ABSCHNITT IS 'Abschnitt';
COMMENT ON COLUMN ABSCHNITT.BEZEICHNUNG IS 'Name des Abschnitts';
COMMENT ON COLUMN ABSCHNITT.BESCHREIBUNG IS 'Beschreibung fuer den Abschnitt';
COMMENT ON COLUMN ABSCHNITT.KOMPLEX IS 'Ist das ein Abschnitt fuer komplexen Variablen oder nicht';

CREATE TABLE ZEILE(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR zeile_seq) PRIMARY KEY,
   CODE	  	  	  NUMBER(4) NOT NULL,
   BESCHREIBUNG   VARCHAR2(80),
   FAKT_TABELLE	  VARCHAR2(50),
   SUMME_LEVEL	  NUMBER(1,0),
   ABSCHNITT_ID   NUMBER(10, 0),
   CONSTRAINT FK_ABSCHNITT FOREIGN KEY (ABSCHNITT_ID) REFERENCES ABSCHNITT (ID)
);

COMMENT ON TABLE ZEILE IS 'Zeile';
COMMENT ON COLUMN ZEILE.CODE IS 'Zeilencode';
COMMENT ON COLUMN ZEILE.BESCHREIBUNG IS 'Beschreibung fuer die Zeile';
COMMENT ON COLUMN ZEILE.FAKT_TABELLE IS 'Name der Fakttabelle';
COMMENT ON COLUMN ZEILE.SUMME_LEVEL IS 'Summe der Level';

CREATE TABLE SPALTE(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR spalte_seq) PRIMARY KEY,
   NUMMER         NUMBER(2) NOT NULL,
   BESCHREIBUNG   VARCHAR2(80),
   FORMAT	  	  VARCHAR2(5),
   ABSCHNITT_ID   NUMBER(10, 0),
   CONSTRAINT FK_SPALTE FOREIGN KEY (ABSCHNITT_ID) REFERENCES ABSCHNITT (ID)
);

COMMENT ON TABLE SPALTE IS 'Spalte';
COMMENT ON COLUMN SPALTE.NUMMER IS 'Spaltennummer';
COMMENT ON COLUMN SPALTE.BESCHREIBUNG IS 'Beschreibung fuer die Spalte';
COMMENT ON COLUMN SPALTE.FORMAT IS 'Format fuer den Wert';

CREATE TABLE VARIABLE
(
   ID 		  	  NUMBER(10, 0) DEFAULT (NEXT VALUE FOR variable_seq) PRIMARY KEY,
   NAME           VARCHAR2(8) NOT NULL,
   AKTIV	  	  NUMBER(1),
   ZEILE_ID	  	  NUMBER(10, 0) NOT NULL,
   SPALTE_ID      NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_VARZEILE FOREIGN KEY (ZEILE_ID) REFERENCES ZEILE (ID),
   CONSTRAINT FK_VARSPALTE FOREIGN KEY (SPALTE_ID) REFERENCES SPALTE (ID)
);

COMMENT ON TABLE VARIABLE IS 'Variable';
COMMENT ON COLUMN VARIABLE.NAME IS 'Name der Variable: Zeile + "s" + Spalte';
COMMENT ON COLUMN VARIABLE.AKTIV IS 'Flag fuer die (de)Aktivierung der Zeile';

CREATE TABLE STEUERSATZ
(
   ID 			  NUMBER(10,0) PRIMARY KEY,
   INTERNALID 	  NUMBER(10) NOT NULL,
   JAHR			  NUMBER(4,0) NOT NULL,
   WERT	 		  NUMBER(6,3),
   GESPERRT		  NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE STEUERSATZ IS 'Konstanten fuer den Steuersatz';
COMMENT ON COLUMN STEUERSATZ.INTERNALID IS 'Interner Schluessel';
COMMENT ON COLUMN STEUERSATZ.JAHR IS 'Gueltig ab dem Jahr';
COMMENT ON COLUMN STEUERSATZ.WERT IS 'Wert des Steuersatzes';
COMMENT ON COLUMN STEUERSATZ.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE EINKOMMEN
(
   ID 			  NUMBER(10,0) PRIMARY KEY,
   INTERNALID 	  NUMBER(10) NOT NULL,
   JAHR			  NUMBER(4,0) NOT NULL,
   WERT 		  NUMBER(10,3),
   BEZEICHNUNG    VARCHAR2(20),
   GESPERRT		  NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE EINKOMMEN IS 'Konstanten fuer die Einkommensermittlung';
COMMENT ON COLUMN EINKOMMEN.INTERNALID IS 'Interner Schluessel';
COMMENT ON COLUMN EINKOMMEN.JAHR IS 'Gueltig ab dem Jahr';
COMMENT ON COLUMN EINKOMMEN.WERT IS 'Wert der Konstante';
COMMENT ON COLUMN EINKOMMEN.BEZEICHNUNG IS 'Bezeichnung der Konstante';
COMMENT ON COLUMN EINKOMMEN.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE BERGGEBIET
(
   ID 			  NUMBER(10,0) PRIMARY KEY,
   INTERNALID 	  NUMBER(10) NOT NULL,
   JAHR			  NUMBER(4,0) NOT NULL,
   GEMEINDE 	  NUMBER(10),
   LANDKREIS 	  NUMBER(10),
   GESPERRT		  NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE BERGGEBIET IS 'Konstanten fuer das Berggebiet';
COMMENT ON COLUMN BERGGEBIET.INTERNALID IS 'Interner Schluessel';
COMMENT ON COLUMN BERGGEBIET.JAHR IS 'Gueltig ab dem Jahr';
COMMENT ON COLUMN BERGGEBIET.GEMEINDE IS 'Gemeinde fuer die Konstante';
COMMENT ON COLUMN BERGGEBIET.LANDKREIS IS 'Landkreis fuer die Konstante';
COMMENT ON COLUMN BERGGEBIET.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE MERKMAL
(
   ID 			  NUMBER(10,0) PRIMARY KEY,
   INTERNALID 	  NUMBER(10) NOT NULL,
   JAHR			  NUMBER(4,0) NOT NULL,
   CODE 		  VARCHAR2(7) NOT NULL,
   BEZEICHNUNG 	  VARCHAR2(150),
   GESPERRT		  NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE MERKMAL IS 'Konstanten fuer die Standard Outputs eines Landkreis';
COMMENT ON COLUMN MERKMAL.INTERNALID IS 'Interner Schluessel';
COMMENT ON COLUMN MERKMAL.JAHR IS 'Gueltig ab dem Jahr';
COMMENT ON COLUMN MERKMAL.CODE IS 'EGANY Code';
COMMENT ON COLUMN MERKMAL.BEZEICHNUNG IS 'Bezeichnung des Merkmals';
COMMENT ON COLUMN MERKMAL.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE STANDARDOUTPUT
(
   ID             NUMBER(10, 0) PRIMARY KEY,
   LANDBEZIRKCODE VARCHAR2(4) NOT NULL,
   OUTPUT         NUMBER(10),
   KONSTANTE_ID	  NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_KONSTANTE FOREIGN KEY (KONSTANTE_ID) REFERENCES MERKMAL (ID) ON DELETE CASCADE
);

COMMENT ON TABLE STANDARDOUTPUT IS 'Standard Output';
COMMENT ON COLUMN STANDARDOUTPUT.LANDBEZIRKCODE IS 'Code des Regierungsbezirks';
COMMENT ON COLUMN STANDARDOUTPUT.OUTPUT IS 'Wert des Standard Outputs';

CREATE TABLE RULES(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR rules_seq) PRIMARY KEY,
   NAME           VARCHAR2(100) NOT NULL,
   PRIORITAET     NUMBER(2, 0),
   TYP            VARCHAR2(20) NOT NULL,
   DATUM 	  	  DATE,
   SKRIPT		  CLOB NOT NULL,
   BEREICH_ID     NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_RULESBEREICH FOREIGN KEY (BEREICH_ID) REFERENCES ERHEBUNGSBEREICH (ID)
);

COMMENT ON TABLE RULES IS 'Regel fuer die Berechnung der komplexen Variablen';
COMMENT ON COLUMN RULES.NAME IS 'Name der Regel';
COMMENT ON COLUMN RULES.PRIORITAET IS 'Prioritaet der Regel, Reihenfolge mit der die Regel ausgefuehrt werden muss';
COMMENT ON COLUMN RULES.TYP IS 'Typ der Regel: EG-Typologie, Brutto-Netto oder sonstiges';
COMMENT ON COLUMN RULES.DATUM IS 'Gueltigkeit der Regel';

CREATE TABLE STATUS
(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR status_seq) PRIMARY KEY,
   WIRTSCHAFTSJAHR  NUMBER(4, 0),
   BESCHREIBUNG	  VARCHAR2(30),
   GESPERRT		  NUMBER(1) DEFAULT 0,
   BEREICH_ID     NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_STATUS_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES BEREICH(ID)
);

COMMENT ON TABLE STATUS IS 'Status einer Sammlung von Betrieben';
COMMENT ON COLUMN STATUS.WIRTSCHAFTSJAHR IS 'Wirtschaftsjahr';
COMMENT ON COLUMN STATUS.BESCHREIBUNG IS 'Status der Sammlung von Betrieben: importiert, mit komplexen Variablen berechnet, hochgerechnet...';
COMMENT ON COLUMN STATUS.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE BETRIEB
(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR betrieb_seq) PRIMARY KEY,
   BETRIEBSNUMMER NUMBER(10) NOT NULL,
   IMPORTZEITPUNKT  DATE,
   BEARBEITER 	  VARCHAR(25),
   LAND		  	  NUMBER(10) NOT NULL,
   BUCHSTELLE	  NUMBER(10) NOT NULL,
   STATUS_ID 	  NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_BETRIEBSTATUS FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID),
   CONSTRAINT BETRIEB_SCHLUESSEL UNIQUE (BETRIEBSNUMMER,LAND,BUCHSTELLE,STATUS_ID)
);

COMMENT ON TABLE BETRIEB IS 'Betrieb mit Metadaten';
COMMENT ON COLUMN BETRIEB.BETRIEBSNUMMER IS 'Betriebsnummer bei der Buchstelle';
COMMENT ON COLUMN BETRIEB.IMPORTZEITPUNKT IS 'Datum von letzten Import des betriebs';
COMMENT ON COLUMN BETRIEB.BEARBEITER IS 'Bearbeiter, der den Betrieb importiert hat';
COMMENT ON COLUMN BETRIEB.LAND IS 'Land';
COMMENT ON COLUMN BETRIEB.BUCHSTELLE IS 'Buchstelle';
COMMENT ON COLUMN BETRIEB.STATUS_ID IS 'Id des Status mit dem Wirtschaftsjahr';

CREATE TABLE BETRIEBSDATEN
(
   ID	  	  	  NUMBER(12, 0) DEFAULT (NEXT VALUE FOR betriebsdaten_seq) PRIMARY KEY,
   VARIABLE   	  VARCHAR2(8) NOT NULL,
   WERT 	  	  NUMBER(19, 5),
   BETRIEB_ID	  NUMBER(10, 0),
   VARIABLE_ID	  NUMBER(10, 0),
   CONSTRAINT FK_ABSCHLUSS FOREIGN KEY (BETRIEB_ID) REFERENCES BETRIEB(ID) ON DELETE CASCADE,
--   CONSTRAINT FK_ABSCHLUSSVARIABLE FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE(ID)
);

COMMENT ON TABLE BETRIEBSDATEN IS 'Buchfuehrungsabschluesse eines Betriebs';
COMMENT ON COLUMN BETRIEBSDATEN.VARIABLE IS 'Variablename mit Kombination von zeilen und spalten';
COMMENT ON COLUMN BETRIEBSDATEN.WERT IS 'Wert fuer die variable';

CREATE TABLE BERECHNUNGSVERSION
(
   ID 			  NUMBER(12, 0) PRIMARY KEY,
   WIRTSCHAFTSJAHR  NUMBER(4,0) NOT NULL,
   RECHENWERTEJAHR	NUMBER(4,0) NOT NULL,
   BESCHREIBUNG	  VARCHAR2(50),
   BERECHNUNGSZEITPUNKT  DATE,
   STATUS		  VARCHAR2(20),
   GESPERRT		  NUMBER(1) DEFAULT 0,
   BEREICH_ID     NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_BV_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES BEREICH (ID),
   CONSTRAINT BERECHNUNGSVERSION_SCHLUESSEL UNIQUE (WIRTSCHAFTSJAHR,RECHENWERTEJAHR,BEREICH_ID)
);

COMMENT ON TABLE BERECHNUNGSVERSION IS 'Version der Berechnung der Komplexen Variablen';
COMMENT ON COLUMN BERECHNUNGSVERSION.WIRTSCHAFTSJAHR IS 'Wirtschaftsjahr';
COMMENT ON COLUMN BERECHNUNGSVERSION.RECHENWERTEJAHR IS 'Jahr der Rechenwerte';
COMMENT ON COLUMN BERECHNUNGSVERSION.BESCHREIBUNG IS 'Beschreibung der Version';
COMMENT ON COLUMN BERECHNUNGSVERSION.BERECHNUNGSZEITPUNKT IS 'Datum der letzten Berechnung';
COMMENT ON COLUMN BERECHNUNGSVERSION.STATUS IS 'Status der letzten Uebertrag ans DWH';
COMMENT ON COLUMN BERECHNUNGSVERSION.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE VERSIONBETRIEB
(
   ID	  	  	  NUMBER(12, 0) PRIMARY KEY,
   KLASSIFIZIERUNG  NUMBER(2, 0) NOT NULL,
   MERKMAL1		  NUMBER(2, 0),
   MERKMAL2		  NUMBER(2, 0),
   MERKMAL3  	  NUMBER(2, 0),
   FILTER		  NUMBER(1),
   PLAUSIBILITAET  NUMBER(2, 0),
   STORNO	  	  NUMBER(2, 0),
   BERECHNUNGSVERSION_ID  NUMBER(10, 0),
   BETRIEB_ID	  NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_BERECHNUNGSVERSION FOREIGN KEY (BERECHNUNGSVERSION_ID) REFERENCES BERECHNUNGSVERSION(ID) ON DELETE CASCADE,
   CONSTRAINT FK_VERSIONBETRIEB_BETRIEB FOREIGN KEY (BETRIEB_ID) REFERENCES BETRIEB(ID) ON DELETE CASCADE
);

COMMENT ON TABLE VERSIONBETRIEB IS 'Version des Betriebs mit einer Kombination Wirtschaftsjahr/Jahr fuer die Standard Outputs';
COMMENT ON COLUMN VERSIONBETRIEB.KLASSIFIZIERUNG IS 'Betriebsystematik (1-60)';
COMMENT ON COLUMN VERSIONBETRIEB.MERKMAL1 IS 'Erstes Merkmal fuer die Berechnung des Filters';
COMMENT ON COLUMN VERSIONBETRIEB.MERKMAL2 IS 'Zweites Merkmal fuer die Berechnung des Filters';
COMMENT ON COLUMN VERSIONBETRIEB.MERKMAL3 IS 'Feld Land fuer Ldw und Fsn fuer die Berechnung des Filters';
COMMENT ON COLUMN VERSIONBETRIEB.FILTER IS 'Boolean Wert, damit der Betrieb bei der Hochrechnung betracht wird (oder nicht)';
COMMENT ON COLUMN VERSIONBETRIEB.PLAUSIBILITAET IS 'Plausibilitaetskennzeichen';
COMMENT ON COLUMN VERSIONBETRIEB.STORNO IS 'Stornokennzeichen';

CREATE TABLE KOMPLEXEVARIABLE
(
   ID	  	  	  NUMBER(12, 0) PRIMARY KEY,
   VARIABLE   	  VARCHAR2(8) NOT NULL,
   WERT 	  	  NUMBER(19, 5),
   VERSIONBETRIEB_ID  NUMBER(10, 0) NOT NULL,
   VARIABLE_ID	  NUMBER(10, 0),
   CONSTRAINT FK_KOMPLEXEVARIABLE FOREIGN KEY (VERSIONBETRIEB_ID) REFERENCES VERSIONBETRIEB(ID) ON DELETE CASCADE,
   CONSTRAINT FK_KOMPLVARVAR FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE(ID)
);

COMMENT ON TABLE KOMPLEXEVARIABLE IS 'Komplexe Variablen eines Betriebs';
COMMENT ON COLUMN KOMPLEXEVARIABLE.VARIABLE IS 'Variablename mit Kombination von zeilen und spalten';
COMMENT ON COLUMN KOMPLEXEVARIABLE.WERT IS 'Wert fuer die variable';

CREATE TABLE GRUNDGESAMTHEIT
(
   ID             NUMBER(10, 0) PRIMARY KEY,
   JAHR	          NUMBER(4, 0) NOT NULL,
   GESPERRT		  NUMBER(1) DEFAULT 0,
   BEREICH_ID     NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_GG_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES BEREICH (ID),
   CONSTRAINT GESAMTHEIT_SCHLUESSEL UNIQUE (BEREICH_ID,JAHR)
);

COMMENT ON TABLE GRUNDGESAMTHEIT IS 'Grundgesamtheit / Hochrechnung zur Bildung der Wichtungsfaktoren';
COMMENT ON COLUMN GRUNDGESAMTHEIT.JAHR IS 'Wirtschaftsjahr';
COMMENT ON COLUMN GRUNDGESAMTHEIT.BEREICH_ID IS 'Fremdschluessel fuer den Bereich: ldw, fis oder fsn';
COMMENT ON COLUMN GRUNDGESAMTHEIT.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE GRUNDGESAMTHEITSDATEN
(
   ID             NUMBER(10, 0) PRIMARY KEY,
   MERKMAL1		  NUMBER(2, 0),
   MERKMAL2	  	  NUMBER(2, 0),
   MERKMAL3  	  NUMBER(2, 0),
   ANZAHL         NUMBER(5, 0),
   GRUNDGESAMTHEIT_ID  NUMBER(10, 0),
   CONSTRAINT FK_GGDATEN FOREIGN KEY (GRUNDGESAMTHEIT_ID) REFERENCES GRUNDGESAMTHEIT (ID) ON DELETE CASCADE
);

COMMENT ON TABLE GRUNDGESAMTHEITSDATEN IS 'Grundgesamtheit / Hochrechnung zur Bildung der Wichtungsfaktoren fuer alle Bereiche';
COMMENT ON COLUMN GRUNDGESAMTHEITSDATEN.MERKMAL1 IS 'ldw: Betriebsform; fsn: Besitzart; fis: Fanggebiet';
COMMENT ON COLUMN GRUNDGESAMTHEITSDATEN.MERKMAL2 IS 'ldw: Groeßenklasse des Betriebs; fsn: Holzbodenflaeche; fis: Laenge, Art';
COMMENT ON COLUMN GRUNDGESAMTHEITSDATEN.MERKMAL3 IS 'Code fuer das Land (1-16; 17=Stadtstaaten 2,4,11); ldw: 17; fsn: 16';
COMMENT ON COLUMN GRUNDGESAMTHEITSDATEN.ANZAHL IS 'Anzahl der Betriebe mit folgenden Attributen';

CREATE TABLE AUSWERTUNGSZEITRAUM
(
   ID			  NUMBER(10, 0) PRIMARY KEY,
   WIRTSCHAFTSJAHR_VON	NUMBER(4, 0) NOT NULL,
   WIRTSCHAFTSJAHR_BIS	NUMBER(4, 0) NOT NULL,
   HOCHRECHNUNGSZEITPUNKT  DATE,
   BEREICH_ID     NUMBER(10, 0) NOT NULL,
   BESCHREIBUNG	  VARCHAR2(50),
   CONSTRAINT FK_ZEITRAUM_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES BEREICH (ID)
);

COMMENT ON TABLE AUSWERTUNGSZEITRAUM IS 'Auswertungszeitraum fuer die Hochrechnung/Berechnung der Gewichtungsfaktoren';
COMMENT ON COLUMN AUSWERTUNGSZEITRAUM.WIRTSCHAFTSJAHR_VON IS 'Jahr fuer den Anfang des Auswertungszeitraums';
COMMENT ON COLUMN AUSWERTUNGSZEITRAUM.WIRTSCHAFTSJAHR_BIS IS 'Jahr fuer das Ende des Auswertungszeitraums';
COMMENT ON COLUMN AUSWERTUNGSZEITRAUM.BESCHREIBUNG IS 'Beschreibung fuer den Auswertungszeitraum';
COMMENT ON COLUMN AUSWERTUNGSZEITRAUM.HOCHRECHNUNGSZEITPUNKT IS 'Datum der letzten Hochrechnung';

CREATE TABLE AUSWAHLVERSIONBETRIEB
(
   ID			  NUMBER(10, 0) PRIMARY KEY,
   AUSWERTUNGSZEITRAUM_ID	NUMBER(10,0) NOT NULL,
   VERSIONBETRIEB_ID  NUMBER(10,0) NOT NULL,
   CONSTRAINT FK_AUSWAHL_AUSWERTUNG FOREIGN KEY (AUSWERTUNGSZEITRAUM_ID) REFERENCES AUSWERTUNGSZEITRAUM(ID) ON DELETE CASCADE,
   CONSTRAINT FK_AUSWAHL_VERSIONBETRIEB FOREIGN KEY (VERSIONBETRIEB_ID) REFERENCES VERSIONBETRIEB(ID) ON DELETE CASCADE
);

COMMENT ON TABLE AUSWAHLVERSIONBETRIEB IS 'Auswahl von Betrieben mit berechneten komplexen Variablen zur Hochrechnung/Berechnung der Gewichtungsfaktoren';

CREATE TABLE GEWICHTUNGSFAKTOR
(
   ID			  NUMBER(10, 0) PRIMARY KEY,
   FAKTOR  		  NUMBER(19, 5) NOT NULL,
   GESPERRT		  NUMBER(1) DEFAULT 0,
   AUSWAHLVERSION_ID  NUMBER(10,0) NOT NULL,
   GRUNDGESAMTHEIT_ID NUMBER(10,0) NOT NULL,
   CONSTRAINT FK_FAKTOR_AUSWAHL FOREIGN KEY (AUSWAHLVERSION_ID) REFERENCES AUSWAHLVERSIONBETRIEB(ID) ON DELETE CASCADE,
   CONSTRAINT FK_FAKTOR_GRUNDGESAMTHEIT FOREIGN KEY (GRUNDGESAMTHEIT_ID) REFERENCES GRUNDGESAMTHEIT(ID)
);

COMMENT ON TABLE GEWICHTUNGSFAKTOR IS 'Gewichtungsfaktor fuer einen Auswahl von Betrieben und eine Grundgesamtheit';
COMMENT ON COLUMN GEWICHTUNGSFAKTOR.FAKTOR IS 'Gewichtungsfaktor aus der Hochrechnung';
COMMENT ON COLUMN GEWICHTUNGSFAKTOR.GESPERRT IS 'Sperrung der Version wegen Veroeffentlichung';

CREATE TABLE LAND
(
   SCHLUESSEL  	  VARCHAR2(2) PRIMARY KEY,
   BUNDESLAND  	  VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE LAND IS 'Bundesland';
COMMENT ON COLUMN LAND.SCHLUESSEL IS 'Schluessel des Bundeslands';
COMMENT ON COLUMN LAND.BUNDESLAND IS 'Name des Bundeslands';

CREATE TABLE BEZIRK
(
   CODE 	  	  VARCHAR2(4) PRIMARY KEY,
   SCHLUESSEL  	  NUMBER(2) NOT NULL,
   NAME		  	  VARCHAR2(50) NOT NULL,
   LAND_SCHLUESSEL 	  VARCHAR2(2) NOT NULL,
   CONSTRAINT FK_BEZIRK FOREIGN KEY (LAND_SCHLUESSEL) REFERENCES LAND(SCHLUESSEL)
);

COMMENT ON TABLE BEZIRK IS 'Regierungsbezirk';
COMMENT ON COLUMN BEZIRK.CODE IS '4 stellige Kombination von Landschluessel und Regierungsbezirksschluessel';
COMMENT ON COLUMN BEZIRK.SCHLUESSEL IS 'Schluessel des Regierungsbezirks';

CREATE TABLE BERICHTSLEVEL
(
   ID             NUMBER(10, 0) DEFAULT (NEXT VALUE FOR berichtslevel_seq) PRIMARY KEY,
   BEZEICHNUNG    VARCHAR2(10) NOT NULL,
   BESCHREIBUNG   VARCHAR2(50)   
);

COMMENT ON TABLE BERICHTSLEVEL IS 'Berichtslevel ?!?';

CREATE TABLE BETRIEBMAPPING
(
   DIMENSIONSTABELLE  	VARCHAR2(30),
   COLUMNNAME 	  		VARCHAR2(30),
   ATTRIBUT_NAME	  	VARCHAR2(30) NOT NULL,
   VARIABLENNAME		VARCHAR2(8) NOT NULL,
   BEREICH				VARCHAR2(10) NOT NULL,
   DEFAULT_VALUE  		NUMBER(2, 0)
);

COMMENT ON TABLE BETRIEBMAPPING IS 'Tabelle fuer das Mapping des Deckblatts';

CREATE TABLE ROLLE
(
   ID             NUMBER(10, 0) PRIMARY KEY,
   NAME			  VARCHAR2(20) NOT NULL,
   BESCHREIBUNG   VARCHAR2(50),
   AKTIV	  	  NUMBER(1)
);

COMMENT ON TABLE ROLLE IS 'Rolle fuer den Anwender/die Anwenderin';
COMMENT ON COLUMN ROLLE.NAME IS 'Name der Rolle';
COMMENT ON COLUMN ROLLE.BESCHREIBUNG IS 'Beschreibung der Rolle';
COMMENT ON COLUMN ROLLE.AKTIV IS 'Gibt an, ob eine Rolle aktiviert ist';

CREATE TABLE ZUGANG
(
   ID             NUMBER(10, 0) PRIMARY KEY,
   ZUGANGSKENNUNG 	VARCHAR2(30) NOT NULL,
   VORNAME	      VARCHAR2(40),
   NACHNAME	      VARCHAR2(40),
   PASSWORT	      VARCHAR2(70),
   AKTIV	  	  NUMBER(1),
   LETZTE_ANMELDUNG DATE,
   ROLLE_ID       NUMBER(10, 0) NOT NULL,
   CONSTRAINT FK_ROLLE FOREIGN KEY (ROLLE_ID) REFERENCES ROLLE(ID),
   CONSTRAINT ZUGANG_EINZIG UNIQUE (ZUGANGSKENNUNG)
);

COMMENT ON TABLE ZUGANG IS 'Rolle fuer den Anwender';
COMMENT ON COLUMN ZUGANG.ZUGANGSKENNUNG IS 'Kennung zur Authentifizierung der Anwenderin/des Anwenders';
COMMENT ON COLUMN ZUGANG.VORNAME IS 'Vorname der Anwenderin/des Anwenders';
COMMENT ON COLUMN ZUGANG.NACHNAME IS 'Nachname der Anwenderin/des Anwenders';
COMMENT ON COLUMN ZUGANG.PASSWORT IS 'Passwort zur Authentifizierung der Anwenderin/des Anwenders';
COMMENT ON COLUMN ZUGANG.AKTIV IS 'Gibt an, ob ein Zugang aktiviert ist';
COMMENT ON COLUMN ZUGANG.LETZTE_ANMELDUNG IS 'Datum der letzten erfolgreichen Anmeldung';

CREATE TABLE JOBPROTOKOLL
(
   ID             NUMBER(10, 0) PRIMARY KEY,
   JOBNAME        VARCHAR2(100) NOT NULL,
   EXECUTIONRESSOURCE	  VARCHAR2(1000) NOT NULL,
   JOBINSTANCERESSOURCE    VARCHAR2(1000) NOT NULL,
   BEREICH_ID     NUMBER(10, 0) NOT NULL,
   BENUTZER VARCHAR2(30) NOT NULL,
   STARTTIME TIMESTAMP NOT NULL,  
   CONSTRAINT FK_JOBPROTOKOLL_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES BEREICH(ID)
);
COMMENT ON TABLE JOBPROTOKOLL IS 'Jobprotokoll Tabelle';

-- Temporäre Tabellen
CREATE TABLE TMP_VERGLEICH
(
   VERSIONBETRIEB_ID  NUMBER(12, 0) PRIMARY KEY,
   BERECHNUNGSVERSION_ID  NUMBER(10, 0) NOT NULL,
   MERKMAL1		  NUMBER(2, 0),
   MERKMAL2		  NUMBER(2, 0),
   MERKMAL3       NUMBER(2, 0)
);

COMMENT ON TABLE TMP_VERGLEICH IS 'Tabelle fuer die Vorbereitung des mehrjaehrigeren Vergleichs';
COMMENT ON COLUMN TMP_VERGLEICH.BERECHNUNGSVERSION_ID IS 'Id der Berechnungsversion';
COMMENT ON COLUMN TMP_VERGLEICH.MERKMAL1 IS 'Erstes Merkmal für die Auswahlsichtgruppe';
COMMENT ON COLUMN TMP_VERGLEICH.MERKMAL2 IS 'Zweites Merkmal für die Auswahlsichtgruppe';
COMMENT ON COLUMN TMP_VERGLEICH.MERKMAL3 IS 'Drittes Merkmal für die Auswahlsichtgruppe';

CREATE TABLE TMP_HOCHRECHNUNG
(
   ID	  	  	  NUMBER(12, 0) PRIMARY KEY,
   GRUNDGESAMTHEIT_ID  NUMBER(10, 0) NOT NULL,
   BERECHNUNGSVERSION_ID  NUMBER(10, 0) NOT NULL,
   MERKMAL1		  NUMBER(2, 0),
   MERKMAL2		  NUMBER(2, 0),
   MERKMAL3       NUMBER(2, 0),
   ANZAHL         NUMBER(5, 0),
   STICHPROBE	  NUMBER(10, 0)
);

COMMENT ON TABLE TMP_HOCHRECHNUNG IS 'Tabelle fuer Berechnung der Gewichtungsfaktor';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.GRUNDGESAMTHEIT_ID IS 'Id der Grundgesamtheit';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.BERECHNUNGSVERSION_ID IS 'Id der Berechnungsversion';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.MERKMAL1 IS 'Erstes Merkmal für die Auswahlsichtgruppe';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.MERKMAL2 IS 'Zweites Merkmal für die Auswahlsichtgruppe';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.MERKMAL3 IS 'Drittes Merkmal für die Auswahlsichtgruppe';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.ANZAHL IS 'Anzahl der Betriebe für die Auswahlsichtgruppe';
COMMENT ON COLUMN TMP_HOCHRECHNUNG.STICHPROBE IS 'Anzahl der Betriebe in der Stichprobe';